name: inovice_gen
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  open_file: ^3.5.10
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.3

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.7.0

  # Local Database
  sqflite: ^2.3.3+1

  # Functional Programming
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
